name: build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_INCREMENTAL: 0
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1
  RUSTFLAGS: -D warnings
  RUSTDOCFLAGS: -D warnings

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Build (all features)
      run: cargo build --features display --verbose
    - name: Run tests (all features)
      run: cargo test --features display --verbose
    - name: Check clippy (all features)
      run: cargo clippy --features display --lib --tests --verbose

    - name: Build (default features)
      run: cargo build --verbose
    - name: Run tests (default features)
      run: cargo test --verbose
    - name: Check clippy (default features)
      run: cargo clippy --lib --tests --verbose

  fmt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Check formatting
      run: cargo fmt --check

  nightly:
    env:
      RUSTDOCFLAGS: -D warnings --cfg docsrs
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install nightly
      run: rustup toolchain add nightly && rustup +nightly component add clippy
    - name: Build docs
      run: cargo +nightly doc --features display --verbose
    - name: Check benches
      run: cargo +nightly clippy --benches --features display --verbose

  regen:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Regen
      run: rm tests/NormalizationTest.txt && cd scripts && python3 unicode.py
    - name: Diff
      run: git update-index --refresh && git diff-index --quiet HEAD --
